export type UserRole = 'OWNER' | 'FAMILY_MEMBER' | 'CONTRACTOR' | 'SERVICE_PROVIDER' | 'ARCHITECT' | 'ADMIN'
export type ProjectStatus = 'PLANNING' | 'ACTIVE' | 'COMPLETED' | 'ARCHIVED'
export type HouseMemberRole = 'OWNER' | 'FAMILY_MEMBER' | 'CONTRACTOR' | 'ARCHITECT'
export type FeatureCategory = 'SECURITY' | 'SMART_HOME' | 'ENERGY' | 'WATER' | 'COMFORT' | 'EXTERIOR' | 'PREMIUM'
export type HouseStageStatus = 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED' | 'COMPLETED_WITH_WARNINGS'
export type TaskType = 'MANDATORY' | 'RECOMMENDED' | 'OPTIONAL'
export type HouseTaskStatus = 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'SKIPPED' | 'BLOCKED'
export type AlertType = 'DEPENDENCY' | 'DECISION' | 'WARNING' | 'BUDGET' | 'PROGRESS' | 'WEATHER'
export type AlertSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
export type MediaType = 'PHOTO' | 'VIDEO'
export type ExpenseCategory = 'ELECTRICAL' | 'PLUMBING' | 'FLOORING' | 'PAINTING' | 'LABOUR' | 'MATERIALS' | 'OTHER'
export type CostConfidence = 'LOW' | 'MEDIUM' | 'HIGH'
export type ReviewReason = 'POOR_QUALITY' | 'DELAYED_WORK' | 'OVER_BUDGET' | 'POOR_COMMUNICATION' | 'OTHER'
export type DocumentType = 'DRAWING' | 'INVOICE' | 'WARRANTY' | 'PLAN' | 'OTHER'
export type WeatherAlertSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
export type Permission =
  | 'house:read' | 'house:write' | 'house:delete' | 'house:manage_members'
  | 'task:write' | 'stage:complete' | 'budget:write' | 'budget:read'
  | 'document:upload' | 'document:delete' | 'document:read'
  | 'progress:submit' | 'progress:verify' | 'decision:write'
  | 'admin:access' | 'provider:manage'
